### ISSUE TITLE
install fails with pip

### ISSUE THREAD

**Issue by bradlipovsky** [tbenthompson/cutde#20] opened 2022-03-15 21:31 UTC
Hi Ben :)

My attempted pip install cutde fails with the following message.  I found a similar result on two different machines, one running linux and one running MacOS.

> Collecting cutde
>   Downloading cutde-21.8.22.tar.gz (622 kB)
>      |████████████████████████████████| 622 kB 22.1 MB/s eta 0:00:01
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... error
>   ERROR: Command errored out with exit status 1:
>    command: /opt/anaconda3/bin/python /opt/anaconda3/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /var/folders/gq/vxjmlz1d29s5k4dk1xkv5p4h0000gn/T/tmpmje7026y
>        cwd: /private/var/folders/gq/vxjmlz1d29s5k4dk1xkv5p4h0000gn/T/pip-install-01251k_6/cutde
>   Complete output (18 lines):
>   Traceback (most recent call last):
>     File "/opt/anaconda3/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
>       main()
>     File "/opt/anaconda3/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
>       json_out['return_val'] = hook(**hook_input['kwargs'])
>     File "/opt/anaconda3/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
>       return hook(config_settings)
>     File "/private/var/folders/gq/vxjmlz1d29s5k4dk1xkv5p4h0000gn/T/pip-build-env-wrfbnrc9/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 177, in get_requires_for_build_wheel
>       return self._get_build_requires(
>     File "/private/var/folders/gq/vxjmlz1d29s5k4dk1xkv5p4h0000gn/T/pip-build-env-wrfbnrc9/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
>       self.run_setup()
>     File "/private/var/folders/gq/vxjmlz1d29s5k4dk1xkv5p4h0000gn/T/pip-build-env-wrfbnrc9/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 281, in run_setup
>       super(_BuildMetaLegacyBackend,
>     File "/private/var/folders/gq/vxjmlz1d29s5k4dk1xkv5p4h0000gn/T/pip-build-env-wrfbnrc9/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 174, in run_setup
>       exec(compile(code, __file__, 'exec'), locals())
>     File "setup.py", line 3, in <module>
>       from pybind11.setup_helpers import STD_TMPL, WIN, Pybind11Extension
>   ModuleNotFoundError: No module named 'pybind11'
>   ----------------------------------------
> ERROR: Command errored out with exit status 1: /opt/anaconda3/bin/python /opt/anaconda3/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /var/folders/gq/vxjmlz1d29s5k4dk1xkv5p4h0000gn/T/tmpmje7026y Check the logs for full command output.

**Comment by tbenthompson** [comment] 2022-03-15 21:58
Brad!! Thanks for this. I'll look into it. 

If you're using conda at all, you could try installing with `conda install -c conda-forge cutde`. In the near future, that will be the primary installation method for `cutde` since it's much more robust to individual machine/environment setup. I need to update the docs (and also fix this pip issue!).

**Comment by tbenthompson** [comment] 2022-03-17 13:20
This should be fixed now. The problem is sometime in the last few versions `pip` moved to defaulting to a PEP517 install system that ignores old dependency management stuff. So, I had to update that. 

That said, I still recommend the conda installation instead of pip. I've now added that to the readme. 

Let me know if you have other problems. 

I'm also curious what you're using cutde for! (feel free to send a private email if you don't want to share publicly)

**Closed** 2022-03-17 13:21 UTC
